# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/examples.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17protobuf/examples.proto\x12\x08\x65xamples"?\n\x0fSimpleItemProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x12\x0e\n\x06\x61\x63tive\x18\x03 \x01(\x08\x62\x06proto3'
)


_SIMPLEITEMPROTO = DESCRIPTOR.message_types_by_name["SimpleItemProto"]
SimpleItemProto = _reflection.GeneratedProtocolMessageType(
    "SimpleItemProto",
    (_message.Message,),
    {
        "DESCRIPTOR": _SIMPLEITEMPROTO,
        "__module__": "protobuf.examples_pb2"
        # @@protoc_insertion_point(class_scope:examples.SimpleItemProto)
    },
)
_sym_db.RegisterMessage(SimpleItemProto)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _SIMPLEITEMPROTO._serialized_start = 37
    _SIMPLEITEMPROTO._serialized_end = 100
# @@protoc_insertion_point(module_scope)
