"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class SimpleItemProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    ACTIVE_FIELD_NUMBER: builtins.int
    name: typing.Text
    amount: builtins.int
    active: builtins.bool
    def __init__(
        self,
        *,
        name: typing.Text = ...,
        amount: builtins.int = ...,
        active: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "active", b"active", "amount", b"amount", "name", b"name"
        ],
    ) -> None: ...

global___SimpleItemProto = SimpleItemProto
