# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cperson.proto\x12\x04main"#\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x62\x06proto3'
)


_PERSON = DESCRIPTOR.message_types_by_name["Person"]
Person = _reflection.GeneratedProtocolMessageType(
    "Person",
    (_message.Message,),
    {
        "DESCRIPTOR": _PERSON,
        "__module__": "person_pb2"
        # @@protoc_insertion_point(class_scope:main.Person)
    },
)
_sym_db.RegisterMessage(Person)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _PERSON._serialized_start = 22
    _PERSON._serialized_end = 57
# @@protoc_insertion_point(module_scope)
